export const routerPaths = {
  DASHBOARD: `/`,
  CUSTOMER_LIST: "/customer/list",
  CUSTOMER_FORM: "/customer/form",
  CATEGORY_LIST: "/category/list",
  CATEGORY_FORM: "/category/form",
  SUBCATEGORY_LIST: "/subcategory/list",
  SUBCATEGORY_FORM: "/subcategory/form",
  PRODUCT_LIST: "/product/list",
  PRODUCT_FORM: "/product/form",
  ORDER_LIST: "/order/list",
  ORDER_FORM: "/order/form",
  SHIPMENT_LIST: "/shipment/list",
  SHIPMENT_FORM: "/shipment/form",
  AUTH_SIGN_IN: "/auth/signIn",
  AUTH_FORGOT_PASSWORD: "/auth/forgotPassword",
  AUTH_RESET_PASSWORD: "/auth/resetPassword/:token",
};

export const linkPaths = {
  DASHBOARD: `/`,
  CUSTOMERS: "/customer/list?page=1&limit=10",
  CUSTOMER: "/customer/form",
  CATEGORIES: "/category/list?page=1&limit=10",
  CATEGORY: "/category/form",
  SUBCATEGORIES: "/subcategory/list?page=1&limit=10",
  SUBCATEGORY: "/subcategory/form",
  PRODUCTS: "/product/list?page=1&limit=10",
  PRODUCT: "/product/form",
  ORDERS: "/order/list?page=1&limit=10",
  ORDER: "/order/form",
  SHIPMENTS: "/shipment/list?page=1&limit=10",
  SHIPMENT: "/shipment/form",
  AUTH_SIGN_IN: "/auth/signIn",
  AUTH_FORGOT_PASSWORD: "/auth/forgotPassword",
  AUTH_RESET_PASSWORD: "/auth/resetPassword/:token",
};
